command.mc.name=mc
command.mc.description=Minecraft release information commands.

command.mc.get.name=get
command.mc.get.description=Get the patch notes for the latest Minecraft release, or a specific release.
command.mc.get.arguments.version.name=version
command.mc.get.arguments.version.description=Release to get patch notes for.

command.mc.versions.name=versions
command.mc.versions.description=Get a list of Minecraft releases.
command.mc.versions.embed.header=Minecraft Releases
command.mc.versions.embed.listItem=- `{item}`
command.mc.versions.embed.footer={number} versions

command.mc.forget.name=forget
command.mc.forget.description=Forget a release version, allowing it to be sent again.
command.mc.forget.done=Version forgotten: `{version}`

command.mc.run.name=run
command.mc.run.description=Check for new Minecraft releases now.
command.mc.run.response=Checking now...

actionLog.threadCreated=Thread created for Minecraft release

buttons.readMore.text=Read more...
embed.truncated=[... {lines} remaining lines]

errors.notReady=Still setting up — try again a bit later!
errors.unknownMcVersion=Unknown version: `{version}`
