commands.message.name=URL Safety Check
commands.slash.name=url-safety-check
commands.slash.description=Check whether a given domain is a known unsafe domain

actions.logMessage=Message contained (or linked to) an unsafe domain

actions.ban.text=you’ve been banned from the server
actions.ban.name=Ban
actions.delete.text=the message was deleted
actions.delete.name=Delete
actions.kick.text=you’ve been kicked from the server
actions.kick.name=Kick
actions.logOnly.text=we logged it for the staff to review
actions.logOnly.name=Log Only

args.domain.name=domain
args.domain.description=Domain to check
args.domain.validationError=Please provide the domain name only, without the protocol or a path.

embed.logging.unsafe.title=Unsafe Domain Detected

notice.message.unsafe=We've detected that the following message contains (or links to) an unsafe domain. For this reason, **{action}**.

response.emoji.unsafe=⚠️
response.emoji.safe=✅

response.domain.unsafe={emoji} `{domain}` is a known unsafe domain.
response.domain.safe={emoji} `{domain}` is **not** a known unsafe domain.

response.message.unsafe={emoji} [Message `{id}`]({url}) **contains {matches} known unsafe link/s**.
response.message.safe={emoji} [Message `{id}`]({url}}) **doesn’t contain any known unsafe links**.

response.matches.header=# Unsafe Domain Matches\n\n**Total:** {matches}
response.matches.filename=matches.md

fields.author=Author
fields.channel=Channel
fields.message=Message
fields.messageId=Message ID
fields.server.name=Server
fields.server.unknown=Unknown Server
fields.totalMatches=Total Matches
fields.actionFailed.name=Action Failed
fields.actionFailed.value=Failed to take action **{action}** because this bot is missing the required permissions, or its top role is below the target's top role.
